---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: grafana
          image: grafana/grafana:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 15
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 2
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          volumeMounts:
            - name: config-volume
              mountPath: /etc/grafana/provisioning/dashboards/provider.yml
              subPath: provider.yml
            - name: dashboards
              mountPath: /etc/dashboards
            - name: data-volume
              mountPath: /var/lib/grafana
        - name: sidecar-dashboards
          image: kiwigrid/k8s-sidecar
          env:
            - name: LABEL
              value: grafana_dashboard
            - name: FOLDER
              value: /etc/dashboards
          resources:
            limits:
              cpu: 100m
              memory: 128M
          volumeMounts:
            - name: dashboards
              mountPath: /etc/dashboards
      volumes:
        - name: config-volume
          configMap:
            name: grafana-config
        - name: dashboards
          emptyDir: {}
        - name: data-volume
          persistentVolumeClaim:
            claimName: grafana-pvc
