---
modules:
  http_2xx:
    http:
      fail_if_not_ssl: true
      method: GET
      preferred_ip_protocol: ip4
      valid_http_versions:
        - HTTP/1.1
        - HTTP/2.0
      valid_status_codes:
        - 200
        - 401
    prober: http
    timeout: 15s
  http_post_2xx:
    http:
      method: POST
    prober: http
  icmp_ping:
    prober: icmp
    icmp:
      preferred_ip_protocol: ip4
