---

- name: get_url - docker gpg apt_key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: 0644
    force: true

- name: apt_repository - docker
  apt_repository:
    # yamllint disable-line rule:line-length
    repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    filename: docker
    state: present
    update_cache: true

- name: apt - containerd.io package
  apt:
    pkg:
      - containerd.io
    state: present

- name: file - /etc/containerd
  file:
    path: /etc/containerd
    state: directory
    mode: 0755

- name: shell - containerd config default > /etc/containerd/config.toml
  shell: containerd config default > /etc/containerd/config.toml

- name: systemd_service - containerd restarted
  systemd_service:
    daemon_reload: true
    name: containerd
    state: restarted
