---

# check state file
- name: stat - /root/.state.cluster.setup
  stat:
    path: /root/.state.cluster.setup
  register: cluster_setup
  tags:
    - always

# System prep
- name: System preparation
  import_tasks:
    system.yml
  tags:
    - system

# Install containerd.io
- name: Intall containerd.io
  import_tasks:
    containerd.yml
  tags:
    - containerd

# Install K8s
- name: Intall k8s
  import_tasks:
    k8s.yml
  tags:
    - k8s

# Reboot, if first time running
- name: reboot
  reboot: {}
  when: not cluster_setup.stat.exists

# touch state file
- name: file - touch /root/.state.cluster.setup
  file:
    path: /root/.state.cluster.setup
    state: touch
