---

# Kernel modules
- name: copy - /etc/modules-load.d/containerd.conf
  copy:
    src: etc/modules-load.d/containerd.conf
    dest: /etc/modules-load.d/containerd.conf

- name: shell - modprobe br_netfilter
  shell: modprobe br_netfilter

- name: shell - modprobe overlay
  shell: modprobe overlay

# Sysctl config
- name: copy - /etc/sysctl.d/99-kubernetes-cri.conf
  copy:
    src: etc/sysctl.d/99-kubernetes-cri.conf
    dest: /etc/sysctl.d/99-kubernetes-cri.conf

- name: shell - sysctl --system
  shell: sysctl --system

# Swap off
- name: lineinfile - .*swap.*
  lineinfile:
    path: /etc/fstab
    regex: '^#?(.*swap.*)'
    line: '#\1'
    backrefs: true

- name: shell - swapoff -a
  shell: swapoff -a
