---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snmp
  namespace: monitoring
  labels:
    app: snmp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snmp
  template:
    metadata:
      labels:
        app: snmp
    spec:
      containers:
        - name: snmp
          image: prom/snmp-exporter
          ports:
            - containerPort: 9116
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 9116
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 15
            successThreshold: 1
            httpGet:
              path: /
              port: 9116
              scheme: HTTP
            timeoutSeconds: 2
          resources:
            limits:
              cpu: 500m
              memory: 256M
