---

all:
  hosts:
    k8s-control:
      ansible_host: 192.168.68.10
    k8s-worker1:
      ansible_host: 192.168.68.11
    k8s-worker2:
      ansible_host: 192.168.68.12
  vars:
    ansible_become: true
    ansible_become_method: sudo
    ansible_user: robertas

    # https://github.com/projectcalico/calico/releases
    k8s_addons:
      calico: v3.27.0

    k8s_release: 1.29
    k8s_version: "{{ k8s_release }}.0"
    k8s_apt_version: "{{ k8s_version }}-1.1"
    k8s_network_cidr: 10.32.0.0/16

control:
  hosts:
    k8s-control:

k8s:
  hosts:
    k8s-control:
    k8s-worker1:
    k8s-worker2:

worker:
  hosts:
    k8s-worker1:
    k8s-worker2:
